name: CI-macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Esy setup
        run: |
          npm install -g esy@latest
          esy install
          esy build --verbosity=debug
